# Generated by Django 2.2.5 on 2020-02-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_heroinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='bpub_data',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='AreaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atitle', models.CharField(max_length=20)),
                ('aParent', models.ForeignKey(blank=True, null=True, on_delete='SET_DEFAULT', to='booktest.AreaInfo')),
            ],
        ),
    ]
