# Generated by Django 2.2.5 on 2020-02-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0003_auto_20200212_0926'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinfo',
            table='bookinfo',
        ),
    ]
